export const skills = [
    'React',
    'MERN Stack',
    'APIs',
    'Node',
    'Express',
    'MySQL', 
    'Sequelize',
    'noSQL',
    'MongoDB', 
    'Mongoose',
    'REST',
    'JavaScript',
    'jQuery',
    'HTML',
    'CSS',
    'Responsive Design',
    'Bootstrap',
    'Tailwind',
    'Handlebars',
    'Progressive Web Applications (PWAs)',
    'Webpack',
    'Socket.io'
]